language: java

jdk:
  - oraclejdk8

before_install:
  - sed -i.bak -e 's|https://nexus.codehaus.org/snapshots/|https://oss.sonatype.org/content/repositories/codehaus-snapshots/|g' $HOME/.m2/settings.xml

install: true

script:
  - ./mvnw clean install -Pall

