language: java

before_install:
  - sed -i.bak -e 's|https://nexus.codehaus.org/snapshots/|https://oss.sonatype.org/content/repositories/codehaus-snapshots/|g' $HOME/.m2/settings.xml
  - sed -i.bak -e 's|http://repo.maven.apache.org/maven2|https://repo.maven.apache.org/maven2|g' $HOME/.m2/settings.xml

install: true

matrix:
  include:
    - jdk: oraclejdk8
      env: PROFILE=jdk8
    - jdk: oraclejdk9
      env: PROFILE=jdk9

script: ./mvnw clean install -Ptest-all-$PROFILE
