== Arquillian Chameleon Container


[quote]
Proxy Container for all JBoss AS / JBoss EAP / WildFly containers

Have you ever faced an issue that switching between container implementations isn't that easy?

Testing against several containers (JBoss AS / JBoss EAP / WildFly) or even switching between different modes (Managed, Remote, Embedded) may result in bloated `pom.xml`.


Chameleon Containers are able to quickly adopt to your needs without too much hassle.

=== Story


[quote]
Chameleons are a tall, lizard-looking alien race that has (same as their earthling friends) ability to change colours when adopting to various environments. They are usually transported in spaceships called Containers.


=== Get Started


Do whatever you http://arquillian.org/guides/getting_started/[would do normally] and add Chameleon Container instead of any application-server specific artifact:

[source, xml]
----
<dependency>
    <groupId>org.jboss.arquillian.junit</groupId>
    <artifactId>arquillian-junit-container</artifactId>
    <scope>test</scope>
</dependency>
<dependency>
    <groupId>org.arquillian.container</groupId>
    <artifactId>arquillian-container-chameleon</artifactId>
    <version>1.0.0.Final-SNAPSHOT</version>
    <scope>test</scope>
</dependency>
----

Add this configuration to `arquillian.xml`:

[source, xml]
----
<container qualifier="chameleon" default="true">
    <configuration>
        <property name="chameleonTarget">wildfly:8.0.0.Final:managed</property>
        <property name="serverConfig">standalone-full.xml</property>
    </configuration>
</container>
----

Now, you can switch container implementation as simple as changing the chameleonTarget configuration option(e.g. `wildfly:8.0.0.Final:remote` or `wildfly:9.0.0.CR1:managed`).

And off course, you can still configure the underlying container by its specific configuration (e.g. change `serverConfig`).

Example chameleonTarget values:

* jboss eap:6.2:remote
* jboss as:7.1.1.Final:managed
* wildfly:9.0.0.Alpha1:embedded

=== Supported Containers

* JBoss EAP
** 6.x
* WildFly
** 9.x
** 8.x
* JBoss AS
** 7.x
* GlassFish
** 3.x
** 4.x

[NOTE]
Chameleon will download and extract the target container if no distribution home is configured and target type is either embedded or managed.

=== Configuration options

==== chameleonTarget

Define the underlying target in the format name:version:type

==== chameleonDistributionDownloadFolder

Override the default download folder for container distributions. Could be defined as 'TMP' to create a custom folder under 'java.io.tmpdir', else
it will be read as a directory. Defaults to detect current build system, either target/ for Maven or bin/ for Gradle.

==== chameleonContainerConfigurationFile

Define the container configuration file to use. Defaults to the containers.yaml file provided by Chameleon.

==== chameleonResolveCacheFolder

Define where Chameleon should store the resolver cache files. By default it will use 'chameleonDistributionDownloadFolder'/cache.

Community
---------

* Chat: #arquillian channel @ http://webchat.freenode.net/[irc.freenode.net]
* http://arquillian.org/blog/[Blogs]
* http://discuss.arquillian.org/[Forums]
